name: janazty
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  get_it: ^9.1.0
  dartz: ^0.10.1
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  firebase_crashlytics: ^5.0.5
  firebase_remote_config: ^6.1.2
  firebase_storage: ^13.0.4
  google_maps_flutter: ^2.14.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  just_audio: ^0.10.5
  audio_service: ^0.18.18
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  shimmer: ^3.0.0
  google_fonts: ^6.3.2
  go_router: ^17.0.0
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  injectable_generator: ^2.8.1
  riverpod_generator: ^3.0.3
  
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
